DOMAIN = "bosch_homecom"
OATUH_DOMAIN = "https://singlekey-id.com"
OATUH_ENDPOINT = "/auth/connect/token"
OATUH_PARAMS = "grant_type=authorization_code&redirect_uri=com.bosch.tt.dashtt.pointt%3A%2F%2Fapp%2Flogin&code_verifier=ll9Q9YRhPBUi6vkM2yTk0gU-D0j7X5RWvYrFcBLF_hYvK8XLB5p_UJ5juSKr5t_YhN2kPDGB6H5aZ8qw25BqLg&client_id=762162C0-FA2D-4540-AE66-6489F189FADC"
OATUH_PARAMS_REFRESH = (
    "grant_type=refresh_token&client_id=762162C0-FA2D-4540-AE66-6489F189FADC"
)
BOSCHCOM_COMPONENTS = [
    "sensor",
]
BOSCHCOM_DOMAIN = "https://pointt-api.bosch-thermotechnology.com"
BOSCHCOM_ENDPOINT_GATEWAYS = "/pointt-api/api/v1/gateways/"
BOSCHCOM_ENDPOINT_FIRMWARE = "/resource/gateway/versionFirmware"
BOSCHCOM_ENDPOINT_NOTIFICATIONS = "/resource/notifications"
BOSCHCOM_ENDPOINT_STANDARD = "/resource/airConditioning/standardFunctions"
BOSCHCOM_ENDPOINT_ADVANCED = "/resource/airConditioning/advancedFunctions"
BOSCHCOM_ENDPOINT_TEMP = "/resource/airConditioning/temperatureSetpoint"
BOSCHCOM_ENDPOINT_MODE = "/resource/airConditioning/operationMode"
BOSCHCOM_ENDPOINT_CONTROL = "/resource/airConditioning/acControl"
BOSCHCOM_ENDPOINT_FULL_POWER = "/resource/airConditioning/fullPowerMode"
BOSCHCOM_ENDPOINT_ECO = "/resource/airConditioning/ecoMode"
BOSCHCOM_ENDPOINT_FAN_SPEED = "/resource/airConditioning/fanSpeed"
BOSCHCOM_ENDPOINT_AIRFLOW_VERTICAL = "/resource/airConditioning/airFlowVertical"
BOSCHCOM_ENDPOINT_AIRFLOW_HORIZONTAL = "/resource/airConditioning/airFlowHorizontal"
BOSCHCOM_ENDPOINT_PLASMACLUSTER = "/resource/airConditioning/airPurificationMode"

ATTR_NOTIFICATIONS = "notifications"
ATTR_FIRMWARE = "fw"
ATTR_MODE = "operationMode"
ATTR_SPEED = "fanSpeed"
ATTR_HORIZONTAL = "airFlowHorizontal"
ATTR_VERTICAL = "airFlowVertical"
ATTR_TEMP = "temperatureSetpoint"
ATTR_ROOM_TEMP = "roomTemperature"
ATTR_AIR_PURIFICATION = "airPurificationMode"
ATTR_FULL_POWER = "fullPowerMode"
ATTR_ECO_MODE = "ecoMode"
ATTR_TIMERS_ON = "timersOn"
ATTR_TIMERS_OFF = "timersOff"
